explain plan set statement_id='tsdb'
for
SELECT SQL_EXTENSIONS.GET_CPD_NAME(R.LIB_ID, R.COMP_ID) NAME, R.LIB_ID, R.COMP_ID,
		 R.COMPLETES_ALL, R.COMPLETES, R.COMPLETES_NFS, R.IGNORES, R.AVG_PCT_FILLED_IN,
		 R.AVG_PCT_RSD, R.AVG_REVERSE_FIT, R.AVG_INTENSITY, R.MIN_INTENSITY, R.MAX_INTENSITY,
		 R.CNT, DECODE(R.COMPLETES, 0, 0, DECODE(R.IGNORES, 0, 100, ROUND(((R.COMPLETES / R.CNT) * 100)))) PCT_COMPLETE
 FROM (SELECT F.LIB_ID, 
        F.COMP_ID, 
        SUM(DECODE(F.STATUS, 'Complete', 1, 'Complete - NFS', 1, 0)) COMPLETES_ALL,
        SUM(DECODE(F.STATUS, 'Complete', 1, 0)) COMPLETES,
        SUM(DECODE(F.STATUS, 'Complete - NFS', 1, 0)) COMPLETES_NFS,
        SUM(DECODE(F.STATUS, 'Ignore', 1, 0)) IGNORES,
        ROUND(AVG(DECODE(F.STATUS, 'Ignore', NULL, F.PCT_FILLED_IN)), 2) AVG_PCT_FILLED_IN,
        ROUND(AVG(DECODE(F.STATUS, 'Ignore', NULL, F.PCT_RSD)), 2) AVG_PCT_RSD,
        NVL(ROUND(AVG(DECODE(F.STATUS, 'Ignore', NULL, F.AVG_REVERSE_FIT)), 2), 0) AVG_REVERSE_FIT,
        ROUND(AVG(DECODE(F.STATUS, 'Ignore', NULL, F.AVG_INTENSITY)), 2) AVG_INTENSITY,
        ROUND(AVG(DECODE(F.STATUS, 'Ignore', NULL, F.MIN_INTENSITY)), 2) MIN_INTENSITY,
        ROUND(AVG(DECODE(F.STATUS, 'Ignore', NULL, F.MAX_INTENSITY)), 2) MAX_INTENSITY,
        COUNT(*) CNT
       FROM (SELECT DISTINCT '(' || C.NAME || ') - [' || P.NAME || '] - ' || SS.NAME STUDY_NAME, T.*
              FROM PROJECTS P, CLIENTS C, SAMPLE_SETS SS, CHRO_CURATION_CPD T 
             WHERE T.STATUS NOT IN('Not Started', 'In Process')
               AND T.SAMPLE_SET_ID = SS.SAMPLE_SET_ID
               AND SS.PROJECT_ID = P.PROJECT_ID
               AND C.CLIENT_ID != 1
               AND P.CLIENT_ID = C.CLIENT_ID) F,
            (SELECT DISTINCT SSE.SAMPLE_SET_ID
              FROM SAMPLE_SET_ENTRY SSE, SAMPLES S
             WHERE SSE.SAMPLE_ID = S.SAMPLE_ID
               AND S.TYPE = 'BMSRC'
               AND S.MATRIX = :B4
               AND S.MATRIX_TYPE = :B3
               AND S.ORGANISM = :B2
               AND S.SPECIES = :B1 ) S1
        WHERE F.LIB_ID = :B6 
          AND F.COMP_ID = :B5
          AND F.SAMPLE_TYPE IN ('EXPERIMENTAL')
          AND S1.SAMPLE_SET_ID = F.SAMPLE_SET_ID 
          GROUP BY F.LIB_ID, F.COMP_ID) R 
ORDER BY PCT_COMPLETE DESC, R.AVG_PCT_RSD
;
@exp9

roll
