explain plan set statement_id='tsdb'
for
SELECT /*+ LEADING (A.t)  */
SUM(DECODE(GREATEST(A.AVG_ROW_LEN,0.8 * B.BLOCK_SIZE ),
A.AVG_ROW_LEN,0,1)),SUM(DECODE(GREATEST(A.AVG_ROW_LEN,0.4 * B.BLOCK_SIZE ),
A.AVG_ROW_LEN,0,1)),SUM(DECODE(GREATEST(A.AVG_ROW_LEN,0.5 * B.BLOCK_SIZE ),
A.AVG_ROW_LEN,0,1)),SUM(DECODE(GREATEST(A.AVG_ROW_LEN,0.6 * B.BLOCK_SIZE ),
A.AVG_ROW_LEN,0,1)),SUM(DECODE(GREATEST(A.AVG_ROW_LEN,0.7 * B.BLOCK_SIZE ),
A.AVG_ROW_LEN,0,1))
   FROM SYS.DBA_TABLES A,(SELECT NAME TABLESPACE_NAME,BLOCKSIZE BLOCK_SIZE
   FROM SYS.TS$ ) B
  WHERE A.CHAIN_CNT > 100
  AND A.CHAIN_CNT > A.NUM_ROWS / 10
   AND A.PARTITIONED= 'NO'
  AND B.TABLESPACE_NAME = A.TABLESPACE_NAME
  AND 250 >=  (SELECT COUNT(*)
   FROM SYS.DBA_TAB_COLUMNS C
  WHERE C.OWNER = A.OWNER
  AND C.TABLE_NAME = A.TABLE_NAME )
;
@exp

roll
